#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	sudo="sudo -A" \
	se="sudo nvim" \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	pwr="sudo powertop" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata --restrict-filenames -i -w" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \

# Colorize commands when possible.
alias \
	l="ls -lhaN --color=auto --group-directories-first" \
	ll="ls -lhaN --color=auto --group-directories-first" \
	lll="ls -lhaN --color=auto --group-directories-first" \

	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	ga="git add -p" \
	gaa="git add ." \
	gs="git status" \
	gc="git checkout" \
	gac="git add . && git commit" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	pac="sudo pacman -Syu" \
	sys="sudo systemctl" \

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	weath="less -S ~/.local/share/weatherreport" \
	z="zathura" \
	gdb="gdb -ex 'set print pretty on'" \
	srv="python2 -m SimpleHTTPServer 8000" \
	memchk="make clean && make && make memcheck" \
	run="make clean && make && make run" \
